import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Container from "./components/Container";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Sidebar from "./components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body id="top" className="min-h-full flex flex-col bg-black">
        <Header />
        <Container>
          {/* MAIN LAYOUT */}
          <div className="flex max-w-7xl mx-auto px-4 gap-8">
            {/* LEFT SIDEBAR */}
            <aside className="hidden lg:block w-[300px]">
              <div className="sticky top-24">
                <Sidebar />
              </div>
            </aside>

            {/* RIGHT CONTENT */}
            <main className="flex-1 min-h-screen">{children}</main>
          </div>
        <Footer />
        </Container>
      </body>
    </html>
  );
}
